const fnKeys = [
  { name: "Escape", nameArr: "Esc" },
  { name: "F1", style: { marginLeft: 62 } },
  { name: "F2" },
  { name: "F3" },
  { name: "F4" },
  { name: "F5", style: { marginLeft: 35 } },
  { name: "F6" },
  { name: "F7" },
  { name: "F8" },
  { name: "F9", style: { marginLeft: 35 } },
  { name: "F10" },
  { name: "F11" },
  { name: "F12" },
];

const mainKeys = [
  { name: "`" },
  { name: "1" },
  { name: "2" },
  { name: "3" },
  { name: "4" },
  { name: "5" },
  { name: "6" },
  { name: "7" },
  { name: "8" },
  { name: "9" },
  { name: "0" },
  { name: "-" },
  { name: "=" },
  { name: "Backspace", style: { width: 90 } },
  { name: "break-line" },
  { name: "Tab", style: { width: 50 } },
  { name: "q" },
  { name: "w" },
  { name: "e" },
  { name: "r" },
  { name: "t" },
  { name: "y" },
  { name: "u" },
  { name: "i" },
  { name: "o" },
  { name: "p" },
  { name: "[" },
  { name: "]" },
  { name: "\\", style: { width: 70 } },
  { name: "break-line" },
  { name: "CapsLock", style: { width: 70 } },
  { name: "a" },
  { name: "s" },
  { name: "d" },
  { name: "f" },
  { name: "g" },
  { name: "h" },
  { name: "j" },
  { name: "k" },
  { name: "l" },
  { name: ";" },
  { name: "'" },
  { name: "Enter", style: { width: 108 } },
  { name: "break-line" },
  { name: "Shift", style: { width: 105 } },
  { name: "z" },
  { name: "x" },
  { name: "c" },
  { name: "v" },
  { name: "b" },
  { name: "n" },
  { name: "m" },
  { name: "," },
  { name: "." },
  { name: "/" },
  { name: "Shift", style: { width: 130 } },
  { name: "break-line" },
  { name: "Control", nameArr: "Ctrl", style: { width: 50 } },
  { name: "Meta", nameArr: "Win", style: { width: 50 } },
  { name: "Alt", style: { width: 50 } },
  { name: " ", style: { width: 290 } },
  { name: "Alt", style: { width: 50 } },
  { name: "Fn", style: { width: 50 } },
  { name: "ContextMenu", nameArr: "Menu", style: { width: 50 } },
  { name: "Control", nameArr: "Ctrl", style: { width: 50 } },
];

const areaKey1 = [
  { name: "PrtSc" },
  { name: "ScrollLock", nameArr: "ScrLk" },
  { name: "Pause" },
];

const areaKey2 = [
  { name: "Insert", nameArr: "Ins" },
  { name: "Home" },
  { name: "PageUp", nameArr: "PgUp" },
  { name: "Delete", nameArr: "Del" },
  { name: "End" },
  { name: "PageDown", nameArr: "PgDn" },
];

const arrowKeys = [
  { name: "empty" },
  { name: "ArrowUp", nameArr: "▲" },
  { name: "empty" },
  {
    name: "ArrowLeft",
    nameArr: "▲",
    style: { justifyContent: "flex-end", transform: "rotate(270deg)" },
  },
  { name: "ArrowDown", nameArr: "▼" },
  {
    name: "ArrowRight",
    nameArr: "▲",
    style: { justifyContent: "flex-start", transform: "rotate(90deg)" },
  },
];

export { fnKeys, mainKeys, areaKey1, areaKey2, arrowKeys };
